version: '3'
services:  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIMES=2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
  hive-server:
    container_name: hive-server
    image: apache/hive:3.1.3
    ports:
      - 10000:10000
    volumes:
      - ./nintendo:/nintendo
      - ./microsoft:/microsoft
      - ./conf-mysql/hive-site.xml:/opt/hive/conf/hive-site.xml
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysqldb://hive-metastore/metastore_db"
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083"
      SERVICE_NAME: hiveserver2
      IS_RESUME: true
    depends_on:
      - hive-metastore

  hive-metastore:
    container_name: hive-metastore
    image: apache/hive:3.1.3
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=mysql
      - HIVE_CUSTOM_CONF_DIR=/conf-mysql
      - IS_RESUME=true
    volumes:
    - ./warehouse:/opt/hive/data/warehouse
    - ./drivers/mysql-connector-java-8.0.19.jar:/opt/hive/lib/mysql-connector-java-8.0.19.jar
    - ./conf-mysql/hive-site.xml:/opt/hive/conf/hive-site.xml
    - ./scripts/entrypoint-mysql.sh:/entrypoint.sh
    ports:
    - 9083:9083
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_DATABASE: metastore_db
      MYSQL_ROOT_HOST: '%'
networks:
 default:
  name: hive